sudo: false
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - build-tools-27.0.1
    - build-tools-28.0.2
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    # for emulating
    - ${ANDROID_TARGET}
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licences:
    - 'android-sdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-28"
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
script:
  - ./gradlew clean build test jacocoTestReport
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - openssl aes-256-cbc -K $encrypted_022658120507_key -iv $encrypted_022658120507_iv -in dist/googleplay-developer-key.json.enc -out dist/googleplay-developer-key.json -d
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew publishBeta
  on:
    tags: true
